/**
 * T-ASM-013 — Field-driven mock for the subscription-transport
 * `ClaudeCliPort` implementation. Mirrors the structural conventions of
 * `MockClaudeCliPort` (SPEC-CCS-001 §6) and the public surface of
 * `ClaudeSubprocessAdapter` (SPEC-ASM-001 §4/§5).
 *
 * Satisfies:
 *   - REQ-ASM-001 (transport-agnostic port construction; no I/O)
 *   - REQ-ASM-031 (session_id capture surface)
 *   - NFR-ASM-006 (startup never throws)
 *   - NFR-ASM-007 (shutdown is idempotent / no-op-safe)
 *
 * Used by `fakeModulePorts()` (ADR-009) and any test that needs a
 * subscription-shaped port without spawning a real `claude` binary.
 *
 * Mock files are permitted to live in the infrastructure layer without
 * importing `obsidian` (ADR-008). The matching ESLint override allows the
 * raw `setTimeout` used to honour `delayMs` for synthetic latency.
 */
import type { CreateFileEnvelope } from '@/application/chat/createFileEnvelopeSchema';
import type { SessionId } from '@/domain/chat/SessionId';
import type {
	ClaudeCliPort,
	ClaudeCliQueryOptions,
	ClaudeCliStreamOptions,
	StreamDelta,
	StructuredCliCallOptions,
	StructuredCliRawResult,
} from '@/domain/ports/ClaudeCliPort';
import { ClaudeCliError } from '@/domain/ports/ClaudeCliPort';
// `ClaudeCliQueryOptions` retained for the `_recordOptions` helper signature.
import type { TransportLifecyclePort } from '@/domain/ports/TransportLifecyclePort';
import type { Result } from '@/domain/shared/Result';
import { err, ok } from '@/domain/shared/Result';

/**
 * Default `cannedStructuredEnvelope` (SPEC-ASM-001 §5.1). A valid `createFile`
 * envelope that round-trips through the Zod schema; tests that need a
 * different shape mutate the field.
 */
const DEFAULT_STRUCTURED_ENVELOPE: CreateFileEnvelope = {
	action: 'createFile',
	path: 'specs/mock/idea.md',
	content: '# Mock idea\n\nGenerated by MockClaudeSubprocessAdapter.\n',
};

/**
 * Recorded options metadata for a single `query()` invocation. Kept as a
 * structurally simple plain object so `JSON.stringify(mock)` surfaces every
 * field — the test harness asserts on serialised mock state to verify that
 * options were threaded through (T-ASM-012 tests #12 / #13).
 */
interface RecordedQueryOptions {
	readonly resumeSessionId: SessionId | null;
	readonly systemPromptSuffix: string | null;
	readonly timeoutMs: number | null;
	readonly maxTurns: number | null;
}

/**
 * Field-driven mock subscription adapter. Every behaviour is configurable
 * through a public field — no constructor arguments, no I/O.
 */
export class MockClaudeSubprocessAdapter implements ClaudeCliPort, TransportLifecyclePort {
	/**
	 * Structural discriminator for `selectTransport()`. Retained as a useful
	 * tag even after WP-12 deleted the `isSubscriptionCapable` guard — the
	 * application layer narrows via `typeof port.runStructured === 'function'`
	 * now, but the selector still keys off `kind`.
	 */
	public readonly kind = 'subscription' as const;

	/**
	 * Drives `isAvailable()` and `isAvailableSync()`. Defaults to `false` so
	 * tests start in the safe degraded state — the standalone browser UI and
	 * any test fixture must opt in explicitly.
	 */
	available = false;

	/**
	 * Text returned from `query()` when `queryError === null`.
	 */
	cannedResponse = '';

	/**
	 * Simulated `session_id` for the subscription transport (REQ-ASM-031).
	 * Settable independently of `cannedResponse`. Default `null` — no session
	 * captured yet.
	 */
	cannedSessionId: SessionId | null = null;

	/**
	 * If non-null, `query()` resolves with this error instead of `cannedResponse`.
	 */
	queryError: ClaudeCliError | null = null;

	/**
	 * Artificial delay (milliseconds) applied before `query()` resolves.
	 * Default `0` — no delay.
	 */
	delayMs = 0;

	/**
	 * Append-only log of every prompt string passed to `query()`. The canonical
	 * assertion surface for "was this prompt sent?" checks.
	 */
	readonly queryLog: string[] = [];

	/**
	 * Append-only log of recorded option metadata for every `query()` call.
	 * Exposed as a public field so `JSON.stringify(mock)` surfaces forwarded
	 * options for test assertions (T-ASM-012 tests #12 / #13).
	 */
	readonly optionsLog: RecordedQueryOptions[] = [];

	/**
	 * Default structured envelope returned by `runStructured()` when
	 * `queryError === null`. `null` simulates "no structured_output present"
	 * — the parser then falls back to the brace-depth scan of `.result` (SPEC
	 * §3.3 step 2). Defaults to a valid sample envelope (§5.1).
	 */
	cannedStructuredEnvelope: CreateFileEnvelope | null = DEFAULT_STRUCTURED_ENVELOPE;

	/**
	 * `.result` field returned alongside `structured_output`. Used to exercise
	 * the fallback parser when `cannedStructuredEnvelope === null`.
	 */
	cannedStructuredRawResult = '';

	/**
	 * Append-only log of `(prompt, options)` recorded for every `runStructured()`
	 * call. Mirrors `queryLog` / `optionsLog` for the structured path.
	 */
	readonly structuredLog: Array<{
		readonly prompt: string;
		readonly options: StructuredCliCallOptions;
	}> = [];

	/** No-op startup — never throws (NFR-ASM-006). */
	async startup(): Promise<void> {
		// Intentionally empty.
	}

	/** No-op shutdown — synchronous, idempotent, never throws (NFR-ASM-007). */
	shutdown(): void {
		// Intentionally empty.
	}

	/** Returns the `available` field. Never throws. */
	async isAvailable(): Promise<boolean> {
		return this.available;
	}

	/**
	 * Synchronous class-only availability accessor (SPEC-ASM-001 §4.2 /
	 * `ClaudeSubprocessAdapter.isAvailableSync`). Performs no I/O — reads the
	 * cached `available` field directly.
	 */
	isAvailableSync(): boolean {
		return this.available;
	}

	/**
	 * Streaming-canonical method (WP-12). Records the prompt/options, honours
	 * `delayMs` interruptibly against `options.signal`, fires the optional
	 * `onSessionId` callback once with `cannedSessionId`, then yields the
	 * configured response as `text` + `done` (or `error` when `queryError`
	 * is set, or `error` on abort).
	 *
	 * Replaces the previous `streamFromQuery`-delegating implementation — that
	 * helper was deleted in WP-12 along with the `query()` method it wrapped.
	 */
	async *queryStream(
		prompt: string,
		options?: ClaudeCliStreamOptions,
	): AsyncIterable<StreamDelta> {
		this.queryLog.push(prompt);
		this._recordOptions(options);

		const signal = options?.signal;
		if (signal?.aborted === true) {
			yield MockClaudeSubprocessAdapter._abortDelta();
			return;
		}

		yield* this._yieldSessionIdIfConfigured(options);

		if (this.delayMs > 0) {
			const aborted = await this._waitOrAbort(signal);
			if (aborted) {
				yield MockClaudeSubprocessAdapter._abortDelta();
				return;
			}
		}

		if (this.queryError !== null) {
			yield { type: 'error', error: this.queryError };
			return;
		}

		if (this.cannedResponse.length > 0) {
			yield { type: 'text', text: this.cannedResponse };
		}
		yield { type: 'done' };
	}

	private static _abortDelta(): StreamDelta {
		return {
			type: 'error',
			error: new ClaudeCliError('QUERY_FAILED', 'Request was aborted'),
		};
	}

	/**
	 * Mirror the real adapter's REQ-ASM-031 contract: surface the canned
	 * session id both as a `session-id` delta AND through the optional
	 * `onSessionId` callback before any text delta. Extracted to keep
	 * `queryStream` under the project complexity ceiling.
	 */
	private async *_yieldSessionIdIfConfigured(
		options: ClaudeCliStreamOptions | undefined,
	): AsyncIterable<StreamDelta> {
		if (this.cannedSessionId === null) return;
		yield { type: 'session-id', sessionId: this.cannedSessionId };
		if (options?.onSessionId !== undefined) {
			try {
				options.onSessionId(this.cannedSessionId);
			} catch {
				// Mock mirrors the real adapter — never let a caller callback throw
				// out of `queryStream()`.
			}
		}
	}

	/**
	 * Sleep `this.delayMs` milliseconds, returning `true` if the signal
	 * aborted before the timer fired. Extracted from `queryStream` to keep
	 * its cyclomatic complexity under the project ceiling.
	 */
	private _waitOrAbort(signal: AbortSignal | undefined): Promise<boolean> {
		return new Promise<boolean>((resolve) => {
			const t = setTimeout(() => {
				signal?.removeEventListener('abort', onAbort);
				resolve(false);
			}, this.delayMs);
			const onAbort = (): void => {
				clearTimeout(t);
				resolve(true);
			};
			signal?.addEventListener('abort', onAbort, { once: true });
		});
	}

	/**
	 * Structural extension of `ClaudeCliPort` per SPEC-ASM-001 §2.9.
	 * Records the (prompt, options) pair, honours `delayMs`, and resolves with
	 * `cannedStructuredEnvelope` packaged into a `StructuredCliRawResult`
	 * (or `queryError` if set). Never throws.
	 *
	 * When `cannedStructuredEnvelope === null`, the returned `structured_output`
	 * is `undefined` so the application-layer parser exercises the
	 * `.result`-fallback path (used by tests of REQ-ASM-024).
	 */
	async runStructured(
		prompt: string,
		options: StructuredCliCallOptions,
	): Promise<Result<StructuredCliRawResult, ClaudeCliError>> {
		this.queryLog.push(prompt);
		this.structuredLog.push({ prompt, options });

		// Mirror the real adapter's REQ-ASM-031 contract for the structured path:
		// when the caller supplies `onSessionId` AND a `cannedSessionId` has been
		// configured, fire the callback exactly once before resolving. This is
		// load-bearing for the proposal-commit pipeline — without it, the active
		// thread keeps `sessionId === null` and `appendProposalDecision` rejects
		// with `SessionLogNoSessionError`.
		if (options.onSessionId !== undefined && this.cannedSessionId !== null) {
			try {
				options.onSessionId(this.cannedSessionId);
			} catch {
				// Mock mirrors the real adapter — never let a caller callback throw
				// out of `runStructured()`.
			}
		}

		if (this.delayMs > 0) {
			await new Promise<void>((resolve) => setTimeout(resolve, this.delayMs));
		}

		if (this.queryError !== null) {
			return err(this.queryError);
		}

		return ok({
			result: this.cannedStructuredRawResult,
			structured_output: this.cannedStructuredEnvelope ?? undefined,
		});
	}

	/**
	 * Records the four ternary-defaulted option fields into `optionsLog`.
	 * Extracted from `query()` so its cyclomatic complexity stays under the
	 * project ceiling — every `?? null` counts as a branch.
	 */
	private _recordOptions(options?: ClaudeCliQueryOptions): void {
		this.optionsLog.push({
			resumeSessionId: options?.resumeSessionId ?? null,
			systemPromptSuffix: options?.systemPromptSuffix ?? null,
			timeoutMs: options?.timeoutMs ?? null,
			maxTurns: options?.maxTurns ?? null,
		});
	}
}
