import type { ContentBlock } from './ContentBlock';
import type { ToolCall } from './ToolCall';

/**
 * A single chat turn — P1 fields + the P2 additive growth (SPEC-CC-004 +
 * SPEC-RR-008). Mirrors the relevant subset of claudian-main `chat.ts:39/46/47`.
 *
 * P2 (rich-rendering, SPEC-RR-008) grows this **additively** with
 * `contentBlocks?`/`toolCalls?`; the six P1 fields are byte-identical. P3
 * (threads-sessions, SPEC-TS-004, ADR-TS-002 §4) grows it additively with the
 * three optional rewind ids `userMessageId`/`assistantMessageId`/
 * `resumeAtMessageId`. The still later-phase members — `images` (P5),
 * `currentNote`, `isInterrupt`/`isRebuiltContext`, `durationFlavorWord` — stay
 * EXCLUDED (ADR-RR-001 §1). "is
 * streaming" and "interrupted" are NOT fields here — the live-turn id and
 * interrupted-turn id live on `chatStore` (SPEC-CC-016) so DTOs stay minimal.
 * No per-block `isExpanded`/timer state on the DTO — that lives in the Vue layer
 * (ADR-003); a stored message replays collapsed-by-default (REQ-RR-012/018).
 * No migration (NFR-RR-010): load-or-default — a P1-shaped stored message (no
 * `contentBlocks`/`toolCalls`) renders unchanged via the P1 path (EC-RR-13).
 *
 * Per-field rules:
 * - `id`: non-empty unique string within the thread; generated by `chatStore`; stable
 *   across re-renders (Vue keys).
 * - `role`: exactly `'user'` or `'assistant'`.
 * - `content`: string; MAY be empty (an interrupted/empty assistant turn, EC-5/EC-8).
 * - `timestamp`: finite epoch-ms number set at creation.
 * - `displayContent` / `durationSeconds`: optional; P1 never renders them (no duration
 *   footer — CLAR-CC-004).
 * - `contentBlocks`: optional, ordered. Absent → render via the P1 `content`/
 *   `MarkdownBlock` path (REQ-RR-012, EC-RR-13). Present → render via `MessageBlocks`.
 * - `toolCalls`: optional. Referenced by `contentBlocks[].toolId`. A `tool_use` block
 *   with no matching `toolCalls` entry renders nothing (EC-RR-1).
 */
export interface ChatMessage {
	id: string;
	role: 'user' | 'assistant';
	content: string;
	timestamp: number;
	displayContent?: string;
	durationSeconds?: number;
	// ---- P2 additive (chat.ts:46/47, SPEC-RR-008) ----
	contentBlocks?: ContentBlock[];
	toolCalls?: ToolCall[];
	// ---- P3 additive (chat.ts:39, SPEC-TS-004, all optional) ----
	/** The runtime's id for this user turn (set on assistant turns it triggered). */
	userMessageId?: string;
	/** The runtime's id for this assistant turn — its PRESENCE proves the runtime processed the turn (REQ-TS-019). */
	assistantMessageId?: string;
	/** The turn id the runtime resumes from for this message (fork/rewind offset). */
	resumeAtMessageId?: string;
}
