/**
 * A single chat turn — P1 subset of claudian-main `chat.ts:39` (SPEC-CC-004).
 *
 * `contentBlocks`, `toolCalls`, `images`, rewind ids, and `currentNote` are EXCLUDED
 * from P1 and regrow P2+. "is streaming" and "interrupted" are NOT fields here — the
 * live-turn id and interrupted-turn id live on `chatStore` (SPEC-CC-016) so DTOs stay
 * minimal and additive.
 *
 * Per-field rules:
 * - `id`: non-empty unique string within the thread; generated by `chatStore`; stable
 *   across re-renders (Vue keys).
 * - `role`: exactly `'user'` or `'assistant'`.
 * - `content`: string; MAY be empty (an interrupted/empty assistant turn, EC-5/EC-8).
 * - `timestamp`: finite epoch-ms number set at creation.
 * - `displayContent` / `durationSeconds`: optional; P1 never renders them (no duration
 *   footer — CLAR-CC-004).
 */
export interface ChatMessage {
	id: string;
	role: 'user' | 'assistant';
	content: string;
	timestamp: number;
	displayContent?: string;
	durationSeconds?: number;
}
