/**
 * merge-vue-sfc-styles esbuild plugin.
 *
 * SFC <style> blocks are extracted by esbuild into main.css (sibling of the JS
 * entry). Obsidian only auto-loads styles.css, so fold the emitted CSS into it
 * under a marker section. Replacing everything after the marker keeps repeated
 * watch-mode rebuilds idempotent. Registered BEFORE copyToObsidian in
 * esbuild.config.mjs (onEnd hooks run in registration order) so the copied
 * styles.css already carries the Vue styles.
 */

import { existsSync, promises as fsPromises, rmSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

// The marker names esbuild.config.mjs (where the plugin is wired) as the
// entry point for readers of styles.css. Never reword it: the string is
// embedded in built styles.css files and idempotent rebuilds depend on
// finding it byte-for-byte.
export const VUE_STYLES_MARKER =
  '\n/* == vue-sfc-styles (generated by esbuild; do not edit — see esbuild.config.mjs) == */\n';

/**
 * Reads styles.css and slices off any previously merged marker section.
 * Returns `{ base, kept }` (full contents / contents before the marker), or
 * null when styles.css does not exist.
 */
async function stylesBeforeMarker(stylesPath) {
  if (!existsSync(stylesPath)) return null;
  const base = await fsPromises.readFile(stylesPath, 'utf8');
  const markerIdx = base.indexOf(VUE_STYLES_MARKER);
  const kept = markerIdx === -1 ? base : base.slice(0, markerIdx);
  return { base, kept };
}

/**
 * @param {{ prod: boolean, esbuild: typeof import('esbuild') }} options
 *   `esbuild` is injected by the config so both sides share one instance.
 */
export function createMergeVueSfcStylesPlugin({ prod, esbuild }) {
  return {
    name: 'merge-vue-sfc-styles',
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length > 0) return;
        const stylesPath = path.join(process.cwd(), 'styles.css');
        const cssPath = path.join(process.cwd(), 'main.css');
        if (!existsSync(cssPath)) {
          // No SFC styles this build: still strip a stale marker section left
          // by a previous watch rebuild so removed <style> blocks actually
          // disappear.
          const styles = await stylesBeforeMarker(stylesPath);
          if (styles && styles.kept !== styles.base) {
            await fsPromises.writeFile(stylesPath, styles.kept, 'utf8');
          }
          return;
        }
        let vueCss = await fsPromises.readFile(cssPath, 'utf8');
        rmSync(cssPath, { force: true });
        rmSync(`${cssPath}.map`, { force: true });
        // Dev builds append an inline sourcemap whose mappings describe
        // main.css, not the merged styles.css — strip it (counterpart of the
        // .map rm above).
        vueCss = vueCss.replace(/\/\*# sourceMappingURL=[\s\S]*?\*\/\s*$/, '');
        if (prod) {
          const minified = await esbuild.transform(vueCss, {
            loader: 'css',
            minify: true,
            legalComments: 'none',
          });
          vueCss = minified.code;
        }
        const styles = await stylesBeforeMarker(stylesPath);
        const kept = styles ? styles.kept : '';
        await fsPromises.writeFile(stylesPath, kept + VUE_STYLES_MARKER + vueCss, 'utf8');
      });
    },
  };
}
